version: '3'

services:
  web:
    container_name: enrollatron
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
