web:
  build: .
  ports:
    - "8000:8000"
  links:
    - db:db
  command: /code/manage.py runserver 0.0.0.0:8000
  stdin_open: true
  tty: true

db:
  image: mysql:latest
  command: mysqld --default-authentication-plugin=mysql_native_password
  environment:
    - MYSQL_DATABASE=django
    - MYSQL_ROOT_PASSWORD=mysql
  ports:
    - "3306:3306"

